---
# tasks file for preinstall
#
- name: Inform user to install docker ansible plugin
  debug:
    msg: "You need to install docker module for your ansible"

- name: wait 10 second
  ansible.builtin.pause:
    seconds: 10

- name: Set timezone
  community.general.timezone:
    name: Etc/UTC

- name: Remove /etc/resolv.conf file
  ansible.builtin.file:
    path: "{{ resolv_conf_path }}"
    state: absent
  ignore_errors: yes

- name: Add DNS into /etc/resolv.conf
  ansible.builtin.template:
    src: "resolv.conf.j2"
    dest: "{{ resolv_conf_path }}"
    owner: "root"
    group: "root"
    mode: "0644"

- name: Set hostname /etc/hostname
  ansible.builtin.lineinfile:
    path: "{{ hostname_path }}"
    regexp: '^.*$'
    line: "{{ inventory_hostname }}"
    state: present

- name: Set hosts /etc/hosts
  ansible.builtin.lineinfile:
    path: "{{ hosts_path }}"
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1 {{ inventory_hostname }} localhost"
    state: present

- name: Add local domain to /etc/hosts
  ansible.builtin.lineinfile:
    path: "{{ hosts_path }}"
    line: "{{ ansible_host }} {{ domain_name }}"

- name: Replace /etc/apt/sources.list file
  ansible.builtin.template:
    src: "apt-sources.list.j2"
    dest: "/etc/apt/sources.list"
    owner: "root"
    group: "root"
    mode: "0644"

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
