---
- name: Restore minio data
  become: true
  block:

    #--------------------------------
    # Minio volume remove and remake
    #--------------------------------
    - name: Stop docker compose stack
      command: docker volume rm {{ minio_volume }} && docker volume create {{ minio_volume }}
      args:
        chdir: "{{ project_path }}"


    #-----------------------------------
    # Restore minio posrgres database
    #-----------------------------------
    - name: Restore minio data from backup
      shell: |
        docker run --rm \
          -v minio-data:/data \
          -v $(pwd):/backup \
          alpine \
          tar xzf backup/{{ backup_file_name }} -C /data

      args:
        executable: /bin/bash


    #------------------------------
    # Minio docker compose restart
    #------------------------------
    - name: Start docker compose stack
      command: docker compose restart
      args:
        chdir: "{{ project_path }}"
