---
- name: Base configuration and installation
  hosts: squid_servers
  become: true
  gather_facts: false

  vars_files:
    - default/group_vars.yml

  pre_tasks:
    - name: Display welcome message
      ansible.builtin.debug:
        msg: "========================================= Squid Proxy Deployment ========================================="

  tasks:
    - name: Ask for deployment action
      ansible.builtin.include_tasks:
        file: tasks/ask.yml
