FROM n8nio/n8n:{{ n8n_version }}

USER root

RUN apk add --no-cache \
    python3 \
    py3-pip \
    bash \
    curl \
    build-base \
    python3-dev \
    libffi-dev \
    openssl-dev

RUN python3 -m venv /opt/python-venv

ENV PATH="/opt/python-venv/bin:$PATH"

RUN pip install --no-cache-dir --upgrade pip setuptools wheel

# If you need other packages add here
RUN pip install --no-cache-dir \
    requests \
    pandas \
    numpy

USER node
