---
- name: Backup Keycloak PostgreSQL database
  hosts: all
  become: yes
  vars_files:
    - defaults/vars.yml

  
  pre_tasks:
    - name: Welcome
      debug:
        msg: "✨✨✨✨✨✨✨✨✨✨ We’re here to help you get backup of your keycloak ✨✨✨✨✨✨✨✨✨✨"

  tasks:
    - include_tasks: tasks/ask.yml