---
# Network  Interface Vars
network:
  interface: "ens33"
  address: "[IP]/[netmask]"
  gateway: "[gateway]"
  dns: "8.8.8.8"


project_path: [project_dir]
backup_dir: "{{ project_path }}/backup"
network_name: keycloak_default
db_user: keycloak
db_name: keycloak
db_password: your_db_password