---
# Network  Interface Vars
network:
  interface: "ens33"
  address: "[IP]/[netmask]"
  gateway: "[gateway]"
  dns: "8.8.8.8"


project_path: [project_dir]
backup_dir: "{{ project_path }}/backup"
network_name: [network-name]
db_user: [db-username]
db_name: [db-name]
db_password: [db-password]

# For restore.yml
backup_file_name: [file_name]