---
- name: Restore keycloak postgres database
  become: true
  block:

    #----------------------------
    # Keycloak docker compose up
    #----------------------------
    - name: Start docker compose once to create database
      command: docker compose up -d
      args:
        chdir: "{{ project_path }}"


    #------------------------------
    # Keycloak docker compose down
    #------------------------------
    - name: Stop docker compose stack
      command: docker compose down keycloak_db
      args:
        chdir: "{{ project_path }}"


    #-----------------------------------
    # Restore keycloak posrgres database
    #-----------------------------------
    - name: Restore Keycloak database from backup
      shell: |
        docker exec -i keycloak_db \
        psql -U {{ db_user }} -d {{ db_name }} \
        < {{ backup_dir }}/{{ backup_file_name }}
      args:
        executable: /bin/bash


    #----------------------------
    # Keycloak docker compose up
    #----------------------------
    - name: Start docker compose stack
      command: docker compose up -d
      args:
        chdir: "{{ project_path }}"
